version = 1
enableSodiumMenu = true
dontCull = []
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
minecraft = true
